### PR TITLE
Upgrade ReasonReact

### PR DESCRIPTION
**Pull request by rusty-key**

### CODE REVIEW

**Review by liubko — COMMENTED** [review]
@rusty-key I'm not sure about this change `_type` => `type_`

https://github.com/reasonml-old/reason-react/blob/master/documentation.md#invalid-prop-name

**Comment by liubko** [comment]
@rusty-key 
https://reasonml.github.io/en/try?rrjsx=true&reason=NoAQRgzgdA9mBWBdAUAUwB4BdUCcB2AhgDYAEAtgQNaoCCJAXCQBTIkkB+A+pgJ4AOqRhEw4AlngDmAXgD8AGlYkArnlGZkAShJSAfCU7aSAIiMBuZMlCRYCFBmz5i5KqgBCDZova8BnISPFpeUUVNU1tPQMpYzMLIlRMEgJDCmoaJi4fVCkjbn5UIzlmDQ1zeMSwFJdXDKzOHLrC4tKgA

**Comment by liubko** [comment]
> The DOM props _type, _open, and others (see 0.4.2 release notes below) are officially removed. Use type_, open_, etc.

oh, ok I now see that in the changelog. 
_But it doesn't really say anything about name mangling when you constructing an object..._

**Comment by rusty-key** [comment]
Yeah, I just decided to follow the convention

**Pull request merged**
